### ISSUE TITLE
flutter_native_splash fails using asset from package

### ISSUE THREAD

**Issue by iapicca** [yakforward-ou/brand#1]
```yaml
name: yakforward
description: "website for yakforward.com"
version: 1.0.0+1
publish_to: "none"
homepage: www.yakforward.com

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: ^3.0.0
  google_fonts: ^6.1.0
  funvas: ^0.1.8
  flutter_svg: ^2.0.10
  meta: ^1.11.0  
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  url_launcher: ^6.2.5
  flutter_hooks: ^0.20.5
  flutter_native_splash: ^2.4.0
  go_router: ^13.2.1

  yakforward_brand:
    git:
      url: https://github.com/yakforward-ou/brand.git
      
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - packages/yakforward_brand/logo.png
    - assets/

flutter_native_splash:
  color: '#FFFFFF'
  image: packages/yakforward_brand/logo.png
  branding: packages/yakforward_brand/logo.png
  android: false
  ios: false
  web: true
```

```console
dart run flutter_native_splash:create
Building package executable... (1.7s)
Built flutter_native_splash:create.
The file "packages/yakforward_brand/logo.png" set as the parameter "image" was not found.
```
